fix(grammarcells): in som cases the cell creation failed when a property attribute was attached
For example, if a concept editor consists of a single property cell wrapped with a wrapper cell,
and a property attribute was attached, then `setBigCell(true)` was called on the cell of the
attribute and not on the property cells.
This resulted in the following exception:

java.lang.AssertionError: "Not big" cell found. Original cell: Collection_p92ya0_a, node: (instance of TEST_AnnotationOnRootProperty_Annotation), concept: com.mbeddr.mpsutil.grammarcells.sandboxlang.structure.TEST_AnnotationOnRootProperty_Annotation. Found cell: property_propertyA, node: (instance of TEST_AnnotationOnRootProperty_Property), concept: com.mbeddr.mpsutil.grammarcells.sandboxlang.structure.TEST_AnnotationOnRootProperty_Property
	at jetbrains.mps.nodeEditor.EditorManager.getUnwrappedNodeBigCell(EditorManager.java:472)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCell_internal(EditorManager.java:419)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCellWithoutAttributes(EditorManager.java:259)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCell(EditorManager.java:272)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.lambda$updateChildNodeCell$2(UpdateSessionImpl.java:225)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.runWithExplicitEditorHints(UpdateSessionImpl.java:347)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.updateChildNodeCell(UpdateSessionImpl.java:225)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.updateChildNodeCell(UpdateSessionImpl.java:214)