Diagram: Deleted the VCS aspect
It causes a NoClassDefFoundError:
jetbrains/mps/vcs/mergehints/runtime/VCSAspectDescriptor
in a command line build.

(cherry picked from commit 43cd48d338fc994c727bbbc95c603223d93de18a)